config/routes.rb
class AdminConstraint
  def self.matches?(request)
    if request.session[:user_id]
      user = User.find request.session[:user_id]
      user && user.admin?
    end
  end
end

Rails.application.routes.draw do
  
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  post 'markdown/preview', to: 'markdown#preview'
  
  root 'books#index'
 
  resources :users, only: [:create] do
    collection do
      get :check_email
      get :check_username
    end
  end
  
  concern :commentable do
    resources :comments, only: [:create]
  end
  
  concern :likeable do 
    resource :like, only: [:create, :destroy]
  end
  
  resources :comments, only: [:edit, :update] do
    member do 
      get :cancel
      delete :trash
    end
  end
  
  resources :notifications, only: [:index, :destroy] do
    collection do
      post :mark
      delete :clear
    end
  end
  
  namespace :settings do
    resource :password, only: [:show, :update]
    resource :account, only: [:show, :update]
    resource :profile, only: [:show, :update]
    resource :notifications,only: [:show, :update]
  end
  
  namespace :users do
    resource :password, only: [:show, :new, :create, :update, :edit]
    resource :confirmation, only: [:new, :show, :create]
  end
  
  resources :books, only: [:index, :show, :new, :create, :edit, :update], concerns: [:commentable, :likeable] do
    collection do
      get 'categoried/:category_id', to: 'books#home', as: :categoried
      get 'search'
      get 'all', to: 'books#home'
    end
  end
  
  resources :attachments, only: [:create]
  
  scope path: '~:username', module: 'users', as: 'user' do
    resources :comments, only: [:index]
    root to: 'books#index'
  end
  
  namespace :admin do
    root to: 'categories#index'
    resources :categories, except: [:edit]
    
    resources :users, only: [:index, :show, :update, :destroy ] do
      collection do 
        get :locked
      end
      member do
        patch :lock
        delete :lock, action: 'unlock'
      end
    end
    resources :books, only: [:index, :show, :update, :destroy ] do
      collection do
        get :locked
      end
      member do
        patch :lock
        delete :lock, action: 'unlock'
      end
    end
  end
  
  constraints(AdminConstraint) do
    mount Resque::Server.new, at: 'resque'
  end
  
end

app/models/book.rb
class Book < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  
  mount_uploader :picture, PictureUploader
  
  belongs_to :user
  belongs_to :category, counter_cache: true
  has_many :comments, as: 'commentable'
  has_many :likes, as: 'likeable'
  
  validates :name, presence: true
  validates :author, presence: true
  
  after_create :update_hot
  after_touch :update_hot
  
  scope :unlocked, -> { where(locked: false) }
  scope :locked, -> { where(locked: true) }
  
  def total_pages
    (comments_count.to_f / Comment.default_per_page).ceil
  end
  
  def liked_by?(user)
    likes.where(user: user).exists?
  end
  
  def lock
    update_attribute :locked, true
  end
  
  def unlock
    update_attribute :locked, false
  end
  
  def locked?
    locked
  end
  
  def calculate_hot
    order = Math.log10([comments_count, 1].max)
    order + created_at.to_f / 45000
  end

  def update_hot
    # reload because comments_count has been cache in associations
    reload
    update_attribute :hot, calculate_hot
  end
  
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < Admin::ApplicationController
  before_action :find_book, except: [:index, :locked]
  
  def index
    @books = Book.unlocked.order(id: :desc).page(params[:page])
  end
  
  def locked
    @books = Book.locked.order(id: :desc).page(params[:page])
    render :index
  end
  
  def lock
    @book.lock
    flash.now[:success] = I18n.t('admin.books.flashes.successfully_locked')
    redirect_to admin_book_path(@book)
  end
  
  def update
    if @book.update_attributes params.require(:book).permit(:name, :author, :price, :picture, :description, :isbn, :category_id)
      flash.now[:success] = I18n.t('admin.books.flashes.successfully_updated')
      redirect_to admin_book_path(@book)
    else
      render :show
    end
  end
  
  def destroy
    @book.destroy
    redirect_to admin_books_path
  end
  
  def unlock
    @book.unlock
    flash.now[:success] = I18n.t('admin.books.flashes.successfully_unlocked')
    redirect_to admin_book_path(@book)
  end
  
  private
  
  def find_book
    @book = Book.find params[:id]
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :find_book, only: [:new, :show, :edit, :update]
  before_action :login_required, :email_confirmed_required, :no_locked_required, only: [:new]
  
  def index
    @books = Book.unlocked.includes(:category).order(id: :desc).page(params[:page])
    
    if params[:category_id]
      @category = Category.where('lower(slug) = ?', params[:category_id].downcase).first!
      @books = @books.where(category: @category)
    end
  end
  
  def home
    @books = Book.unlocked.order(id: :desc).page(params[:page])
    
    if params[:category_id]
      @category = Category.where('lower(slug) = ?', params[:category_id].downcase).first!
      @books = @books.where(category: @category)
    end
  end
  
  def search
    @books = Book.unlocked.search(
    query: {
      multi_match: {
        query: params[:q].to_s,
        fields: ['name', 'author']
      }
    }
    ).page(params[:page]).records
  end
  
  def new
    @category = Category.where('lower(slug) = ?', params[:category_id].downcase).first if params[:category_id].present?
    @book = Book.new category: @category
  end
  
  def create
    @book = current_user.books.create book_params
    if @book.save
      flash[:success] = I18n.t('.books.create.new_book_submitted')
      redirect_to @book
    else
      render :new
    end
  end
  
  def show
    @book = Book.find params[:id]
    @comments = @book.comments.includes(:user).order(id: :asc).page(params[:page])
    
    respond_to do |format|
      format.html
    end
  end
  
  def update
    if @book.update_attributes book_params
      flash[:success] = I18n.t('.books.update.book_updated')
      redirect_to @book
    else
      render :edit
    end
  end
  
  private
  
  def find_book
    @book = Book.find_by(id: params[:id])
  end
  
  def book_params
    params.require(:book).permit(:name, :author, :price, :picture, :description, :isbn, :category_id)
  end
end

app/controllers/users/books_controller.rb
class Users::BooksController < Users::ApplicationController
  def index
    @books = @user.like_books.order(id: :desc).page(params[:page])
  end
end

app/helpers/books_helper.rb
module BooksHelper
  def book_last_path(book)
    book_path(book, page: (book.total_pages if book.total_pages > 1), anchor: (book.comments_count if book.comments_count > 0))
  end
end

app/views/admin/books/index.html.erb
<% @page_title = t('.books') %>
<div class="sub-navbar">
	<ul class="nav sub-navbar-nav">
		<li class="<%= 'active' if action_name == 'index' %>">
			<a href="<%= admin_books_path %>">
				<%= t('.normal') %>
			</a>
		</li>
		<li class="<%= 'active' if action_name == 'locked' %>">
			<a href="<%= locked_admin_books_path %>">
				<%= t('.locked') %>
			</a>
		</li>
	</ul>
</div>
<div class="main">
	<div class="container">
		<%= render 'share/flash_messages' %>
		<div class="row">
			<div class="col-md-8 col-md-push-2">
				<div class="panel">
					<div class="panel-heading">
						<h2 class="panel-title">
							<%= t('.books') %>
						</h2>
					</div>
					<div class="panel-body">
						<div class="list-group list-group-hepte">
							<% @books.each do |book| %>
								<a class="list-group-item" href="<%= admin_book_path(book) %>">
									<div class="list-group-item-heading">
										<%= book.id %>.
										<b><%= book.name %></b>
									</div>
								</a>
							<% end %>
						</div>
					</div>
					<div class="panel-footer clearfix">
						<% paginate @books, theme: 'hepte' %>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/admin/books/show.html.erb
<div class="sub-navbar">
	<ul class="nav sub-navbar-nav">
		<li class="<%= 'active' if action_name == 'index' %>">
			<a href="<%= admin_books_path %>">
				<%= t('.normal') %>
			</a>
		</li>
		<li class="<%= 'active' if action_name == 'locked' %>">
			<a href="<%= locked_admin_books_path %>">
				<%= t('.locked') %>
			</a>
		</li>
	</ul>
</div>
<div class="main">
	<div class="container">
		<div class="row">
			<div class="col-md-8">
				<div class="panel">
					<div class="panel-heading">
						<h1 class="panel-title"><%= @book.name %></h1>
					</div>
					<div class="panel-body book">
						<div class="col-sm-3 pull-right">
								<img class="img" src="<%= @book.picture.cover.url %>"></img>
						</div>
						<div class="col-sm-6">
							<div id="info">
									<span class="pl"><%= t('.author') %>: </span><%= @book.author %><br>
									<span class="pl"><%= t('.price') %>: </span><%= @book.price %><br>
									<span class="pl pull-right"><%= t('.isbn') %>:</span> <%= @book.isbn %>
							 </div>
						</div>
						<div class="description">
							<h3><%= t('.description') %>:</h3>
							<article class="comment-body">
								<%= @book.description %>
							</article>
						</div>
					</div>
					<div class="panel-footer" data-creator-id="<%= @book.user_id %>">
						<% if login? %>
						<div class="list-group-item-actions">
							<a class="btn" href="<%= edit_book_path(@book) %>">
								<i class="fa fa-pencil"></i>
							</a>
							<% if @book.locked? %>
								<a class="btn" href="<%= lock_admin_book_path(@book) %>" data-method="delete">
									<i class="fa fa-unlock"></i>
								</a>
							<% else %>
								<a class="btn" href="<%= lock_admin_book_path(@book) %> " data-method="patch" >
									<i class="fa fa-lock"></i>
								</a>
							<% end %>
						</div>
						<% end %>
					</div>
				</div>
			</div>
			<div class="col-md-4">
				
			</div>
		</div>
	</div>
</div>