config/routes.rb
class AdminConstraint
  def self.matches?(request)
    if request.session[:user_id]
      user = User.find request.session[:user_id]
      user && user.admin?
    end
  end
end

Rails.application.routes.draw do
  
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  post 'markdown/preview', to: 'markdown#preview'
  
  root 'books#index'
 
  resources :users, only: [:create] do
    collection do
      get :check_email
      get :check_username
    end
  end
  
  concern :commentable do
    resources :comments, only: [:create]
  end
  
  concern :likeable do 
    resource :like, only: [:create, :destroy]
  end
  
  resources :comments, only: [:edit, :update] do
    member do 
      get :cancel
      delete :trash
    end
  end
  
  resources :notifications, only: [:index, :destroy] do
    collection do
      post :mark
      delete :clear
    end
  end
  
  namespace :settings do
    resource :password, only: [:show, :update]
    resource :account, only: [:show, :update]
    resource :profile, only: [:show, :update]
    resource :notifications,only: [:show, :update]
  end
  
  namespace :users do
    resource :password, only: [:show, :new, :create, :update, :edit]
    resource :confirmation, only: [:new, :show, :create]
  end
  
  resources :books, only: [:index, :show, :new, :create, :edit, :update], concerns: [:commentable, :likeable] do
    collection do
      get 'categoried/:category_id', to: 'books#home', as: :categoried
      get 'search'
      get 'all', to: 'books#home'
    end
  end
  
  resources :attachments, only: [:create]
  
  scope path: '~:username', module: 'users', as: 'user' do
    resources :comments, only: [:index]
    root to: 'books#index'
  end
  
  namespace :admin do
    root to: 'categories#index'
    resources :categories, except: [:edit]
    
    resources :users, only: [:index, :show, :update, :destroy ] do
      collection do 
        get :locked
      end
      member do
        patch :lock
        delete :lock, action: 'unlock'
      end
    end
    resources :books, only: [:index, :show, :update, :destroy ] do
      collection do
        get :locked
      end
      member do
        patch :lock
        delete :lock, action: 'unlock'
      end
    end
  end
  
  constraints(AdminConstraint) do
    mount Resque::Server.new, at: 'resque'
  end
  
end

app/views/share/_flash_messages.html.erb
<% [:success, :info, :warning, :danger].each do |type| %>
	<% if flash[type] %>
		<div class="alert alert-<%= type %>">
			<%= flash[type] %>
			<a class="close" data-dismiss="alert">&times;</a>
		</div>
	<% end %>
<% end %>

app/views/share/_form_error_messages.html.erb
<% if form.object.errors.any? %>
	<div class="alert alert-warning">
		<a class="close" data-dismiss="alert">
			&times;
		</a>
		<% form.object.errors.full_messages.each do |message| %>
			<p><%= message %></p>
		<% end %>
	</div>
<% end %>

app/views/share/_user_confirm_required.html.erb
<div id="user-confirm-required">
	<div class="container">
		<div class="alert alert-warning">
			<p><%= t '.description', email: current_user.email %></p>
			<p>
				<a class="btn btn-default" href="<%= users_confirmation_path %>" data-remote="true" data-method="post"><%= t('.resend_email') %></a>
				<a class="btn" href="<%= settings_account_path %>"><%= t('.change_email') %></a>
			</p>
		</div>
		<div id="user-confirm-required-modal" class="modal fade">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<button class="close" data-dismiss="modal">
							&times;
						</button>
						<div class="modal-title">
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/share/form_error_messages.html.erb
<% if form.object.errors.any? %>
	<div class="alert alert-warning">
		<a class="close" data-dismiss="alert">
			&times;
			<% form.object.errors.full_messages.each do |message| %>
			<p><%= message %></p>
			<% end %>
		</a>
	</div>
<% end %>