config/routes.rb
class AdminConstraint
  def self.matches?(request)
    if request.session[:user_id]
      user = User.find request.session[:user_id]
      user && user.admin?
    end
  end
end

Rails.application.routes.draw do
  
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  post 'markdown/preview', to: 'markdown#preview'
  
  root 'books#index'
 
  resources :users, only: [:create] do
    collection do
      get :check_email
      get :check_username
    end
  end
  
  concern :commentable do
    resources :comments, only: [:create]
  end
  
  concern :likeable do 
    resource :like, only: [:create, :destroy]
  end
  
  resources :comments, only: [:edit, :update] do
    member do 
      get :cancel
      delete :trash
    end
  end
  
  resources :notifications, only: [:index, :destroy] do
    collection do
      post :mark
      delete :clear
    end
  end
  
  namespace :settings do
    resource :password, only: [:show, :update]
    resource :account, only: [:show, :update]
    resource :profile, only: [:show, :update]
    resource :notifications,only: [:show, :update]
  end
  
  namespace :users do
    resource :password, only: [:show, :new, :create, :update, :edit]
    resource :confirmation, only: [:new, :show, :create]
  end
  
  resources :books, only: [:index, :show, :new, :create, :edit, :update], concerns: [:commentable, :likeable] do
    collection do
      get 'categoried/:category_id', to: 'books#home', as: :categoried
      get 'search'
      get 'all', to: 'books#home'
    end
  end
  
  resources :attachments, only: [:create]
  
  scope path: '~:username', module: 'users', as: 'user' do
    resources :comments, only: [:index]
    root to: 'books#index'
  end
  
  namespace :admin do
    root to: 'categories#index'
    resources :categories, except: [:edit]
    
    resources :users, only: [:index, :show, :update, :destroy ] do
      collection do 
        get :locked
      end
      member do
        patch :lock
        delete :lock, action: 'unlock'
      end
    end
    resources :books, only: [:index, :show, :update, :destroy ] do
      collection do
        get :locked
      end
      member do
        patch :lock
        delete :lock, action: 'unlock'
      end
    end
  end
  
  constraints(AdminConstraint) do
    mount Resque::Server.new, at: 'resque'
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  include Gravtastic
  gravtastic secure: true, default: 'wavatar', rating: 'G', size: 48
  mount_uploader :avatar, AvatarUploader
  
  has_secure_password
  has_many :books
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :delete_all
  has_many :likes, dependent: :delete_all
  has_many :like_books, through: :likes, source: :likeable, source_type: 'Book'
  has_many :attachments, dependent: :delete_all
  
  validates :username, uniqueness: { case_sensitive: false }, presence: true, format: { with: /\A[a-z0-9][a-z0-9-]*\z/i }
  validates :email, uniqueness: { case_sensitive: false }, presence: true, format: { with: /\A([^@\s]+)@((?:[a-z0-9-]+\.)+[a-z]{2,})\z/i }
  
  scope :unlocked, -> { where(locked_at: nil) }
  scope :locked, -> { where.not(locked_at: nil) }
  
  def admin?
    CONFIG['admin_emails'] && CONFIG['admin_emails'].include?(email)
  end
  
  def lock
    update_attribute :locked_at, current_time_from_proper_timezone
  end
  
  def unlock
    update_attribute :locked_at, nil
  end
  
  def locked?
    locked_at.present?
  end
  
  def self.verifier_for(purpose)
    @verifiers ||= {}
    @verifiers.fetch(purpose) do |p|
      @verifiers[p] = Rails.application.message_verifier("#{self.name}-#{p.to_s}")
    end
  end
  
  def password_reset_token
    self.class.verifier_for('password-reset').generate([id, Time.now])
  end
  
  def self.find_by_password_reset_token(token)
    user_id, timestamp = verifier_for('password-reset').verify(token)
    User.find_by(id: user_id) if timestamp > 1.hour.ago
  rescue ActiveSupport::MessageVerifier::InvalidSignature
    nil
  end
  
  def confirm
    update_attribute :confirmed, true
  end

  def confirmation_token
    self.class.verifier_for('confirmation').generate([id, email, Time.now])
  end

  def self.find_by_confirmation_token(token)
    user_id, email, timestamp = verifier_for('confirmation').verify(token)
    User.find_by(id: user_id, email: email) if timestamp > 1.hour.ago
  rescue ActiveSupport::MessageVerifier::InvalidSignature
    nil
  end
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  before_action :find_user, except: [:index, :locked]
  
  def index
    @users = User.unlocked.order(id: :desc).page(params[:page])
  end
  
  def locked
    @users = User.locked.order(id: :desc).page(params[:page])
    render :index
  end
  
  def show
  end
  
  def update
    if @user.update_attributes params.require(:user).permit(:name, :username, :email, :confirmed, :bio, :avatar, :remove_avatar)
      flash[:success] = I18n.t('admin.users.flashes.successfully_updated')
      redirect_to admin_user_url(@user)
    else
      render :show
    end
  end
  
  def destroy
    @user.destroy
    flash[:success] = I18n.t('admin.users.flashes.successfully_destroy')
    redirect_to admin_users_path
  end
  
  def lock
    @user.lock
    flash[:success] = I18n.t('admin.users.flashes.successfully_locked')
    redirect_to admin_user_url(@user)
  end
  
  def unlock
    @user.unlock
    flash[:success] = I18n.t('admin.users.flashes.successfully_unlocked')
    redirect_to admin_user_url(@user)
  end
  
  private
  
  def find_user
    @user = User.find params[:id]
  end
end

app/controllers/users/application_controller.rb
class Users::ApplicationController < ApplicationController
  before_action :find_user

  private

  def find_user
    @user = User.where('lower(username) = ?', params[:username].downcase).first!
  end
end

app/controllers/users/books_controller.rb
class Users::BooksController < Users::ApplicationController
  def index
    @books = @user.like_books.order(id: :desc).page(params[:page])
  end
end

app/controllers/users/comments_controller.rb
class Users::CommentsController < Users::ApplicationController
  def index
    @comments = @user.comments.includes(:commentable).order(id: :desc).page(params[:page])
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < ApplicationController
  before_action :login_required, :no_confirmed_required
  before_action :access_limiter, only: [:create]
  
  def show
    if params[:token].present?
      @user = User.find_by_confirmation_token(params[:token])
      if @user && @user == current_user
        @user.confirm
        flash.now[:success] = I18n.t('users.confirmations.confirm_success')
        redirect_to root_url
      end
    end
  end

  def create
    UserMailer.confirmation(current_user.id).deliver
  end

  private

  def no_confirmed_required
    if current_user.confirmed?
      redirect_to root_url
    end
  end
  
  def access_limiter
    key = "verifies:limiter:#{request.remote_ip}"
    if $redis.get(key).to_i > 0
      render :limiter
    else
      $redis.incr(key)
      if $redis.ttl(key) == -1
        $redis.expire(key, 60)
      end
    end
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < ApplicationController
  before_action :no_login_required
  before_action :check_token, only: [:edit, :update]
  
  def new
  end
  
  def create
    if @user = User.where('lower(email) = lower(?)', params[:email]).first
      UserMailer.password_reset(@user.id).deliver
      redirect_to users_password_path
    else
      flash.now[:warning] = I18n.t('passwords.flashes.user_email_not_found')
      redirect_to root_url
    end
  end
  
  def edit
  end

  def update
    if @user.update_attributes params.require(:user).permit(:password, :password_confirmation)
      flash[:success] = I18n.t('passwords.flashes.successfully_update')
      redirect_to login_url
    else
      render :edit
    end
  end
  
  private 
  
  def check_token
    unless @user = User.find_by_password_reset_token(params[:token])
      flash[:warning] = I18n.t('passwords.flashes.token_invalid')
      redirect_to new_users_password_path
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.order(id: :desc)
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new params.require(:user).permit(:name, :username, :email, :password)
    if @user.save
      login_as @user
      UserMailer.confirmation(@user.id).deliver
      redirect_to root_url
    else
      render 'new'
    end
  end
  
  def check_email
    respond_to do |format|
      format.json do
        render json: !User.where('lower(email) = ?', params[:user][:email].downcase).where.not(id: params[:id]).exists?
      end
    end
  end

  def check_username
    respond_to do |format|
      format.json do
        render json: !User.where('lower(username) = ?',  params[:user][:username].downcase).where.not(id: params[:id]).exists?
      end
    end
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
  def user_link(user)
    user_root_path(username: user.username)
  end
end

app/views/admin/users/index.html.erb
<% @page_title = t('.users') %>
<div class="sub-navbar">
	<ul class="nav sub-navbar-nav">
		<li class="<%= 'active' if action_name == 'index' %>">
			<a href="<%= admin_users_path %>">
				<%= t('.normal') %>
			</a>
		</li>
		<li class="<%= 'active' if action_name == 'locked' %>">
			<a href="<%= locked_admin_users_path %>">
				<%= t('.locked') %>
			</a>
		</li>
	</ul>
</div>
<div class="main">
	<div class="container">
		<%= render 'share/flash_messages' %>
		<div class="row">
			<div class="col-md-8 col-md-push-2">
				<div class="panel">
					<div class="panel-heading">
						<h2 class="panel-title">
							<%= t('.users') %>
						</h2>
					</div>
					<div class="panel-body">
						<div class="list-group list-group-hepte">
							<% @users.each do |user| %>
								<a class="list-group-item" href="<%= admin_user_path(user) %>">
									<div class="list-group-item-heading">
										<%= user.id %>.
										<b><%= user.name %></b>
										<span class="text-muted">@<%= user.username %></span>
									</div>
									<div class="text-muted">
										<%= user.email %>
									</div>
								</a>
							<% end %>
						</div>
					</div>
					<div class="panel-footer clearfix">
						<% paginate @users, theme: 'hepte' %>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/admin/users/show.html.erb
<% @page_title = @user.name %>
<div class="main">
	<div class="container">
		<div class="row">
			<div class="col-md-8 col-md-push-2">
				<div class="panel">
					<div class="panel-heading">
						<h2 class="panel-title">
							<%= @user.name %>
						</h2>
					</div>
					<div class="panel-body">
						<%= form_for [:admin, @user], html: { multipart: true, class: 'user-form'} do |f| %>
							<%= render 'share/flash_messages' %>
							<%= render 'share/form_error_messages', form: f %>
							<div class="form-group">
								<%= f.label :avatar, class: 'control-label' %>
								<div class="user-image-uploader">
									<div class="image">
										<img class="img-rounded" alt="avatar" src="<%= @user.avatar.bigger.url %>">
									</div>
									<div class="uploader">
										<%= f.file_field :avatar %>
										<div class="check_box">
											<label><%= f.check_box :remove_avatar %></label>
											<%= t('.remove_avatar') %>
										</div>
									</div>
								</div>
							</div>
							<div class="form-group">
								<%= f.label :name %>
								<%= f.text_field :name, class: 'form-control', tabIndex: 1 %>
							</div>
							<div class="form-group">
								<%= f.label :username %>
								<%= f.text_field :username, class: 'form-control', tabIndex: 2 %>
							</div>
							<div class="form-group">
								<%= f.label :email %>
								<%= f.text_field :email, class: 'form-control', tabIndex: 3 %>
							</div>
							<div class="form-group">
								<div class="checkbox">
									<label>
										<%= f.check_box :confirmed %>
										<%= t('.confirmed') %>
									</label>
								</div>
							</div>
							<div class="form-group">
								<%= f.label :bio %>
								<%= f.text_area :bio, class: 'form-control', tabIndex: 4 %>
							</div>
							<div class="form-group">
								<%= f.label :created_at %>
								<%= f.text_field :created_at, class: 'form-control', disabled: true  %>
							</div>
							<% if @user.locked? %>
								<div class="form-group">
                	<%= f.label :locked_at %>
                	<%= f.text_field :locked_at, class: 'form-control', disabled: true %>
								</div>
							<% end %>
							<div class="clearfix">
								<%= f.submit t('.save_changes'), class: 'btn btn-success', tabIndex: 5 %>
								<div class="pull-left">
									<% if @user.locked? %>
										<a class=" btn btn-default" href="<%= lock_admin_user_path(@user) %>" data-method="delete">
										<%= t('.unlock') %>
										</a>
									<% else %>
										<a class=" btn btn-default" href="<%= lock_admin_user_path(@user) %>" data-method="patch">
										<%= t('.lock') %>
										</a>
									<% end %>
								</div>
							</div>
						<% end %>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script>
$('form.user-form').validate({
  rules: {
    'user[name]': {
      required: true,
    },
    'user[email]': {
      required: true,
      format: /^([^@\s]+)@((?:[a-z0-9-]+\.)+[a-z]{2,})$/i,
      remote: '/users/check_email?id=#{@user.id}'
    },
    'user[username]': {
      required: true,
      remote: '/users/check_username?id=#{@user.id}',
      format: /^[a-z0-9-]+$/i
    },
    'user[password]': {
      required: true
    }
  },
  messages: {
    'user[name]': {
      required: '#{@user.errors.generate_message :name, :blank}'
    },
    'user[email]': {
      required: '#{@user.errors.generate_message :email, :blank}',
      remote: '#{@user.errors.generate_message :email, :taken}',
      format: '#{@user.errors.generate_message :email, :format}'
    },
    'user[username]': {
      required: '#{@user.errors.generate_message :username, :blank}',
      remote: '#{@user.errors.generate_message :username, :taken}',
      format: '#{@user.errors.generate_message :username, :format}'
    }
  }
});
</script>